[project]
name = "dbt-basics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mohan Raj", email = "mohanrajgurunathann@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dbt-core>=1.12.0",
    "dbt-databricks>=1.12.3",
]

[project.scripts]
dbt-basics = "dbt_basics:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
